### ISSUE TITLE
Can those .sh run without gpu?

### ISSUE THREAD

**Issue by waldstein1983** [laiguokun/LSTNet#1]
Dear authors,
I want to run it on cpu and remove "--gpu 3" from the *.sh, but having following error:
16619.36172750017
number of parameters: 325871
begin training
TypeError: slice indices must be integers or None or have an __index__ method,
on 
File "/Users/baohuaw/PycharmProjects/LSTNet/models/LSTNet.py", line 52, in forward
    s = c[:,:, -self.pt * self.skip:].contiguous();
Can you please help?
Thx.

**Comment by laiguokun** [comment]
You can check this issue #2.

Best
